const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');
const dataDir = path.join(process.cwd(), 'data');
const parts = fs.readdirSync(dataDir).filter((name) => /^catalog\.part\d+\.b64$/.test(name)).sort();
if (!parts.length) throw new Error('No catalog parts found.');
const packed = parts.map((name) => fs.readFileSync(path.join(dataDir, name), 'utf8')).join('');
const catalog = JSON.parse(zlib.gunzipSync(Buffer.from(packed, 'base64')).toString('utf8'));
if (!Array.isArray(catalog.offers) || catalog.offers.length !== 140) throw new Error(`Expected 140 offers, found ${catalog.offers?.length ?? 0}.`);
fs.writeFileSync(path.join(dataDir, 'catalog.json.gz.b64'), packed);
console.log(`Built and validated runtime catalog from ${parts.length} parts: ${catalog.offers.length} offers.`);
