const assert = require('node:assert/strict');
const core = require('../api/_core');
assert.equal(core.offers.length, 140);
const summary = core.summary();
assert.equal(summary.counts.offers, 140);
assert.equal(summary.counts.categories, 29);
assert.ok(core.filterOffers({ category:'AI tools' }).length > 0);
assert.ok(core.recommend({ country:'SE', school_email:true, github_verified:true }, 'web-development', 10).recommendations.length > 0);
assert.ok(core.buildStack({ country:'SE', school_email:true, github_verified:true }, 'student-startup', 8).offers.length > 0);
console.log(JSON.stringify({ ok:true, offers:core.offers.length, categories:summary.counts.categories }, null, 2));
